# Rename this file to languages.toml to enable multilingual support
[en]
    languageName      = "English"
    languagedirection = "ltr"
    title             = "Ming8087's Blog"
    weight            = 1

[zh-cn]
languageName      = "中文"
languagedirection = "ltr"
title             = "Ming8087的博客"
weight            = 2
